#pragma once

#define DEVICE_NAME L"RegProtector"

#define IOCTL_REGKEY_PROTECT_ADD	CTL_CODE(0x8000, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REGKEY_PROTECT_REMOVE	CTL_CODE(0x8000, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REGKEY_PROTECT_CLEAR	CTL_CODE(0x8000, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)


const int MaxRegNameSize = 300;
struct RegKeyProtectInfo {
	WCHAR KeyName[MaxRegNameSize]{};
};
